[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
num-bigint = {version="0.4.3", features=["rand"]}
num-traits = "0.2"

[dev-dependencies]
aes = "0.8.1"

[lib]
doctest = false
