[package]
name = "challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
aes = "0.8.1"
rand = "0.8.5"

[dev-dependencies]
mersenne_twister = "1.1.1"

[lib]
doctest = true
