[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
challenges = { path = "../challenges" }

[[bin]]
name = "main"
path = "./main.rs"
test = false
